<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="assets\icon.ico"/>
  </ItemGroup>
</Project>
